### ISSUE TITLE
Reconsider name for function to obtain underlying data - get(), value()...

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/type-lite#5]
See also this [survey](https://twitter.com/tvaneerd/status/950834553425338368) by Tony Van Eerd.
‏
>StrongType<int, MyTag> st;
>
>member function (in addition to static_cast) that *gets* the *underlying* *value* inside the strong type:
>
>int x = ...
>39% st.get();
>42% st.value();
>06% st.underlying();
>13% st.unwrap();
>325 votes•Final results

**Comment by tvaneerd** [comment]
I settled on `get` by the way.  It follows my new naming rule of "consistent use of warning signs".  `get()` has become a warning sign for unwrapping an abstraction (like smart ptr get()), and we want the same warning sign here.

**Comment by martinmoene** [comment]
Keeping it at `get()`.
